baseurl      = "https://www.aradhyamehta.com"
title        = "Aradhya Mehta"
languageCode = "en-us"
theme        = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate     = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = true
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[author]
  name = "Aradhya Mehta"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  
# Metadata mostly used in document's head
  description = "Personal Webpage using hugo themes"
  keywords = ""
  images = [""]

  homeSubtitle = "Software Engineer"

  disableReadOtherPosts = false

  enableThemeToggle = true

  enableSharingButtons = true

  customCSS = []
  customJS  = []

  justifyContent = false  # Set "text-align: justify" to .post-content.

  [params.footer]
    trademark = true
    rss = false
    copyright = true
    author = true

    topText = []
    bottomText = ["Powered by <a href=\"http://gohugo.io\">Hugo</a>",
            "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"]

  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoMark     = ">"
    logoText     = "$Home"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/aradhya_mehta/"

  [[params.social]]
    name = "email"
    url  = "mailto:nobody@example.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/aradhyamehta/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/aradhya-mehta/"

[languages]
  [languages.en]
    subtitle  = "Personal Webpage"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"